# Generated by Django 4.1.2 on 2022-10-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=240)),
                ('fullname', models.CharField(max_length=240)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=240)),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=240)),
                ('fullname', models.CharField(max_length=240)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=240)),
                ('image', models.TextField()),
            ],
        ),
    ]
