# Generated by Django 4.1.2 on 2022-10-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_users_image_alter_shops_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shops',
            old_name='password',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='shops',
            old_name='fullname',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='shops',
            old_name='username',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='shops',
            old_name='email',
            new_name='shopname',
        ),
        migrations.AlterField(
            model_name='shops',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
