# Generated by Django 4.1.2 on 2022-10-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_password_shops_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='shopname',
            field=models.CharField(max_length=50),
        ),
    ]
