# Generated by Django 4.1.2 on 2022-10-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_shops_shopname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
    ]
